### ISSUE TITLE
Scope patients on `GetPatientListRequest` for wards instead of the organization

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/services#389]
### Describe the feature

[GetPatientListRequest](https://proto.helpwave.de/#proto.services.task_svc.v1.GetPatientListRequest) should be scoped by a ward instead of the organization.

### Why is this feature needed?

_Discussed with the medical team. An organization wide patient list makes sense but only as a separate feature._

### Additional context

https://github.com/helpwave/web/issues/663

**Comment by DasProffi** [comment]
This probably entails altering the patients table in the db as otherwise unassigned patients wouldn't be visible in the patientlist anymore.
Do we want to add the ward id or just replace the organization_id?
None the less this will also affect other methods like assigning a patient to bed, as this could place the patient in a different ward then he is currently scoped to

**Comment by MaxSchaefer** [comment]
I would propose a mix of organization and ward scoped patients in the patient list. This requires no change to the patient model, just the queries. IMO this makes also more sense due to the fact that we don't bind patients yet to a ward and an unassigned can be moved quicker between wards. @helpwave/medical 
 
__Active__: Patients that are assigned to a bed of the passed ward
__UnassignedPatients__: Patients of the organization of the passed ward where that are not assigned to a bed and where `is_discharged` is set to false 
__DischargedPatients__: Patients of the organization of the passed ward where `is_discharged` is set to true
